@startuml

hide circle
hide empty members

entity Vehicle {
*id (VehicleService)
}

entity Device {
*id
}

entity Report {
*id
---
*timestamp
*mileage
*fuel_economy
*distance_travelled
}

Vehicle ||--o{ Report
Vehicle ||--|{ Device
@enduml
