@startuml

hide circle
hide empty members

entity Vehicle {
*id
*owner_id (AccountService)
*driver_id (AccountService)
---
*manufacturer
*model
*fuel_type
*img_location
*weight
*date_of_production
*license_plate
}

entity Device {
*id
}

entity Report {
*id
---
*timestamp
*mileage
*fuel_economy
*distance_travelled
}

Vehicle ||--|{ Device

Vehicle ||--o{ Report

@enduml
